version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: backend-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}

  ws:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ws
    container_name: ws-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    container_name: web-frontend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}

volumes:
  pgdata:
